### ISSUE TITLE
The application doesn't work out of the box

### ISSUE THREAD

**Issue by AliaksandrKot** [GidsOpenStandaarden/OpenPGO-Medmij-ImplementatieBouwstenen-Java#2]
Hi there,

I tried to run the application as you can understand I didn't achieve the success.
I followed by you instructions from `README` file.
The first error was on validatio phase:
```
Exception in thread "main" org.xml.sax.SAXParseException; cvc-complex-type.2.3: Element 'MedMijNode' cannot have character [children], because the type's content type is element-only.
	at java.xml/com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(ErrorHandlerWrapper.java:204)
	at java.xml/com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.error(ErrorHandlerWrapper.java:135)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:396)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:327)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:284)
	at java.xml/com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaValidator$XSIErrorReporter.reportError(XMLSchemaValidator.java:511)
	at java.xml/com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaValidator.reportSchemaError(XMLSchemaValidator.java:3587)
	at java.xml/com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaValidator.elementLocallyValidComplexType(XMLSchemaValidator.java:3472)
	at java.xml/com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaValidator.elementLocallyValidType(XMLSchemaValidator.java:3432)
	at java.xml/com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaValidator.processElementContent(XMLSchemaValidator.java:3334)
	at java.xml/com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaValidator.handleEndElement(XMLSchemaValidator.java:2372)
	at java.xml/com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaValidator.endElement(XMLSchemaValidator.java:943)
	at java.xml/com.sun.org.apache.xerces.internal.jaxp.validation.DOMValidatorHelper.finishNode(DOMValidatorHelper.java:341)
	at java.xml/com.sun.org.apache.xerces.internal.jaxp.validation.DOMValidatorHelper.validate(DOMValidatorHelper.java:246)
	at java.xml/com.sun.org.apache.xerces.internal.jaxp.validation.DOMValidatorHelper.validate(DOMValidatorHelper.java:189)
	at java.xml/com.sun.org.apache.xerces.internal.jaxp.validation.ValidatorImpl.validate(ValidatorImpl.java:108)
	at java.xml/javax.xml.validation.Validator.validate(Validator.java:124)
	at nl.zorgdoc.medmij.Whitelist.<init>(Whitelist.java:41)
	at nl.zorgdoc.medmij.XML.fromURL(XML.java:61)
	at nl.zorgdoc.medmij.Whitelist.fromUrl(Whitelist.java:50)
	at nl.zorgdoc.medmij.App.main(App.java:20)
```
I've figured out that the xml deffinitions form `http://gids.samenbeter.org/openpgoexamples/1.0/whitelist-voorbeeld-v1.0.xml` and `Whitelist.xsd` are different and I've adjusted them(I can create the PR if it's needed)
After this I had to adjust the fetching the list of hosts for whitelist in `Whitelist.java:64`
and added 
`l = (NodeList) xpath.compile("//w:MedMijNode/text()").evaluate(d, XPathConstants.NODESET);`.
Finnaly I got the whitelist.

But after all, the provided example (from `README`) for receiving the token throws an error:
`Exception: java.net.UnknownHostException: medmij.xisbridge.net`

The same error you can see in `README`.

I'm wondering to receive this token :)

**Comment by relitodea** [comment]
Please use the version 1.1 - the given example file is for test purposes and compatible with 1.0. The new library is 1.1 compatible. Example XML's are provided in the resource folder.

**Comment by AliaksandrKot** [comment]
still the same problems with `xsd`

**Comment by relitodea** [comment]
This is a library and not a complete working example of MedMij. The Server side does not exist so the java.net.UnknownHostException: medmij.xisbridge.net is expected. Again.. this is an example on how to use the library and not a runtime environment.

**Comment by relitodea** [comment]
I have updated the readme to use the version 1.1 - please let me know is this works now.

**Comment by AliaksandrKot** [comment]
Now there are no problems with `XSD` and XML in general.
But I still don't understand why using this(or library) I cannot receive the token.
there is `Zal` from with the `library` finally gets the `tokenEndpointuri`.
For all of the elements of `zal`  we have `78834.umcharderwijk.nl` or `medmij.xisbridge.net` as a endpoint.
Is there the possibility to test the receiving the token?

In general, I understand which way I have to follow to achieve it, but can I somehow test in on real (maybe test) server like `78834.umcharderwijk.nl` or `medmij.xisbridge.net`

**Comment by relitodea** [comment]
I'm sorry. .that is not is in the scope of the library. We do not have a test system - you will need to create your own server side Auth.

**Comment by AliaksandrKot** [comment]
Thanks for the support. 

One notion form guy not from Netherland, It would be good to have at least `JavaDocs` with a small explanation the Dutch terminologies or variables 👍
